name: Create a Kiota GitHub Pre Release

on:
  workflow_dispatch:
    inputs:
      repository-owner:
        description: 'Repository owner to release from'
        required: true
        default: 'microsoft'
      repository-name:
        description: 'Repository name to release from'
        required: true
        default: 'kiota'
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  publish_binaries:
    name: Publish binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - win-x64
          - win-x86
          - linux-x64
          - osx-x64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Publish ${{ matrix.architecture }}
        run: dotnet publish ./src/kiota/kiota.csproj -c Release -p:PublishSingleFile=true -r ${{ matrix.architecture }} -o ./${{ matrix.architecture }}
      - name: Archive Release ${{ matrix.architecture }}
        uses: thedoctor0/zip-release@master
        working-directory: ./${{ matrix.architecture }}
        with:
          filename: "./${{ matrix.architecture }}.zip"
          path: "./*"
      - uses: actions/upload-artifact@v3
        working-directory: ./${{ matrix.architecture }}
        with:
          name: binaries-${{ matrix.architecture }}
          path: ./${{ matrix.architecture }}.zip
  create_release:
    name: Create Release
    needs: [publish_binaries]
    environment:
      name: gh_releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
      - id: version
        run: echo "version=v0.0.0-pre+${{ github.event.inputs.repository-owner }}.${{ github.event.inputs.branch }}.$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v3
        with:
          path: output
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: ${{ steps.version.outputs.version }}
          body: "Kiota PreRelease ${{ github.event.inputs.repository }}@${{ github.event.inputs.branch }}"
          files: |
            output/binaries-*/*.zip
